## Version à utiliser pour docker compose, dépend de votre version de Docker. Deux version majeure
## Version 2 => Non compatible avec swarm (Orchestrateur de conteneur)
## Versio 3.XX => Compatible Swarm
version: '3.7'

services:
    apache1:
        build: ./../dockerfiles/serveurApache/
        ## On associe le container apache1 à la fois au reseau reseau_apache_1 et au reseau reseau_apache_2
        networks: 
            - reseau_apache_1
            - reseau_apache_2
        links:
            - app


    apache2:
        build: ./../dockerfiles/serveurApache/       
        networks: 
            - reseau_apache_1            
        

    apache2:
        build: ./../dockerfiles/serveurApache/       
        networks: 
            - reseau_apache_1            
        

    db:
        image: mysql:5.7
        container_name: mysql_c
        restart: always
        volumes:
            - db-volume:/var/lib/mysql
            - ./articles.sql:/docker-entrypoint-initdb.d/articles.sql
        environment:
            MYSQL_ROOT_PASSWORD: test
            MYSQL_DATABASE: test
            MYSQL_USER: test
            MYSQL_PASSWORD: test

    app:
        image: myapp
        container_name: myapp_c
        restart: always
        networks: 
            - reseau_apache_2
        volumes:
            - ./app:/var/www/html
        ports:
            - 8080:80
        depends_on:
            - db

volumes:
    db-volume:

networks:
    reseau_apache_1:
        name: reseau_apache_1
    reseau_apache_2:
        name: reseau_apache_2